### ISSUE TITLE
I created a flutter module and use flutter_keyboard_visibility ,reported an error MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility)

### ISSUE THREAD

**Issue by 15949893621** [MisterJimson/flutter_keyboard_visibility#111]
![截屏2022-05-23 15 57 06](https://user-images.githubusercontent.com/17999816/169771561-2787a290-591a-429e-8115-28c7161a687d.png)
created a flutter module，As is shown in. You can reproduce the problem

**Comment by MisterJimson** [comment]
This typically happens when the Flutter project isn't created properly. If its still an issue can you reopen with a reproducible test case?
