### ISSUE TITLE
Change of Copyright notice

### ISSUE THREAD

**Issue by julia410m** [MisterJimson/flutter_keyboard_visibility#118]
Hello! Can you change Copyright notice in your MIT License (software flutter_keyboard_visibility, flutter_keyboard_visibility_platform_interface, flutter_keyboard_visibility_web) and add the author's name and surname, according to the conditions of the license's application. Now it is unreal to identify the copyright owner of your software. Thank you in advance

**Comment by MisterJimson** [comment]
Done! Thanks for the notice.
