### ISSUE TITLE
Android gradle 8 break change in 5.4.2

### ISSUE THREAD

**Issue by fabricio-godoi** [MisterJimson/flutter_keyboard_visibility#132]
I just get an error because of the version management of your package. In version 5.4.2 we got a breaking change of the gradle dependency since you update it to gradle 8. I don't get the need for it since [Flutter itself uses 7.6.1 in its guidelines](https://docs.flutter.dev/release/breaking-changes/android-java-gradle-migration-guide), nevertheless, it is recommended that you upgrade to the major version of your package when a breaking change is added in the package (e.g. version 6.0.0).

I hope that further versions are handled with care.

To whom it may interest, we fixed the version in our project to 5.4.1 in the pubspec without the `^` character.

````yaml
  fluttter_keyboard_visibility: 5.4.1
````

**Comment by MisterJimson** [comment]
My apologies. I'll look into this today.

**Comment by MisterJimson** [comment]
5.4.3 should support both Gradle 7 and 8. We now use 7.6.1 as in the guidelines.
