### ISSUE TITLE
Flutter 3.10 breaks, please help fix

### ISSUE THREAD

**Issue by luohao123** [MisterJimson/flutter_keyboard_visibility#137]
```
A problem occurred evaluating project ':flutter_keyboard_visibility'.
> Could not find method disable() for arguments [InvalidPackage] on task ':flutter_keyboard_visibility:lint'
```

**Comment by MisterJimson** [comment]
What version are you using?

**Comment by jv-soares** [comment]
Same here, using 5.4.1 and gradle 7.5

**Comment by MisterJimson** [comment]
Are you pinning 5.4.1 or do you have it in your pubspec as ^5.4.1?

**Comment by jv-soares** [comment]
ˆ5.4.1 in pubspec

**Comment by MisterJimson** [comment]
Change it to just 5.4.1 and pub get, that should update your lock file to the correct version

**Comment by luohao123** [comment]
I am afraid is not about version , its lib using old gradle but most **i mean almost** updated flutter libs are using gradle 7.5+ but this lib is very old, cosnider update it

**Comment by luohao123** [comment]
@MisterJimson Consider it.

**Comment by Macacoazul01** [comment]
> Change it to just 5.4.1 and pub get, that should update your lock file to the correct version

@MisterJimson it didn't solve the problem here

**Comment by allenlinli** [comment]
May I know what's the highest Flutter/Gradle/Java version being supported so far?
I am running on Flutter 3.13.1/Gradle/Gradle 8.3/JVM21 and couldn't continue.

**Comment by MisterJimson** [comment]
I had positive feedback on the beta so 6.0.0 is live.
