### ISSUE TITLE
Keyboard is not detected in Android

### ISSUE THREAD

**Issue by emersonsiega** [MisterJimson/flutter_keyboard_visibility#14]
I'm using this library since Flutter v1.0 and always worked fine... some time ago I updated to Flutter stable and to flutter_keyboard_visibility 0.8.0/2.0.0 due to AndroidX compatibility, and after that, the lib doesn't work anymore...

In iOS works fine..

My project was generated with Java for Android and Objective-C for iOS.

Was tested on devices listed bellow.

`flutter doctor`
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale pt-BR)
    • Flutter version 1.12.13+hotfix.5 at /Users/emerson.siega/development/flutter
    • Framework revision 27321ebbad (5 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/emerson.siega/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/emerson.siega/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • MotoG3                    • 0020798379                           • android-arm • Android 6.0 (API 23)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 7.0 (API 24) (emulator)
    • iPhone SE                 • 366E752D-695F-4490-9DF6-0AD88E142BA9 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

**Comment by MisterJimson** [comment]
Thanks for the report!

Do you see any errors printed in the logs while running the app?

Does the example in this project work for you?

**Comment by emersonsiega** [comment]
> Do you see any errors printed in the logs while running the app?

Nope. Just doesn't fire the methods and I just can't know if keyboard is visible or hidden.

  
> Does the example in this project work for you?

It's working fine.

**Comment by MisterJimson** [comment]
Thanks for the info. I've created a new branch `update-platform-projects` where recreated the Android Java project based on the new release of Flutter which has some structure changes. It still seems to work for me.

Is it just this plugin having issues? If you don't have manual changes in your Android project you could delete everything in the /android folder and run `flutter create -a java .` To recreate it based on the latest Flutter code.

**Comment by emersonsiega** [comment]
Same problem https://github.com/MisterJimson/flutter_keyboard_visibility/issues/15

**Comment by omidraha** [comment]
Same issue, Always return `True` for this sample [example](https://github.com/MisterJimson/flutter_keyboard_visibility/blob/729af885ac94b32c045e88120492596a2d65c051/flutter_keyboard_visibility/example/lib/main.dart#L1)
