### ISSUE TITLE
Android : Namespace not specified. Please specify a namespace in the module's build.gradle file like so

### ISSUE THREAD

**Issue by hiteshsarsava** [MisterJimson/flutter_keyboard_visibility#141]
**Describe the bug**
Build Issue in Android

**To Reproduce**
Installed the version 5.4.1 and not able compile or run the project.

**Expected behavior**
Should compile and Run

**Logs*
FAILURE: Build failed with an exception.

```
* What went wrong:
A problem occurred configuring project ':flutter_keyboard_visibility'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }

     If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 35s
Exception: Gradle task assembleDebug failed with exit code 1
```

![image](https://github.com/MisterJimson/flutter_keyboard_visibility/assets/16486943/90069708-ed98-4788-8812-2e4d4fad3b78)

**Comment by DrBu7cher** [comment]
This is "fixed", just not in a release yet. So the next release will fix it - I am just wondering, when this will be?

**Comment by DrBu7cher** [comment]
https://github.com/MisterJimson/flutter_keyboard_visibility/blob/master/flutter_keyboard_visibility/android/build.gradle#L26
It's fixed since 3 months, but something broke
https://github.com/MisterJimson/flutter_keyboard_visibility/pull/131#issuecomment-1555118363
so it got reverted.
https://github.com/MisterJimson/flutter_keyboard_visibility/issues/132#issuecomment-1555915501
And the fix did not show up in pub.dev.
https://github.com/MisterJimson/flutter_keyboard_visibility/pull/133#issuecomment-1576479483
So I suggest you add the following to your pubspec.yaml:
```yaml
dependency_overrides:
  flutter_keyboard_visibility:
    git:
      url: https://github.com/MisterJimson/flutter_keyboard_visibility.git
      ref: b5e7b0de4fa9eb6a6c076f1120e5f92a77b7679d # https://github.com/MisterJimson/flutter_keyboard_visibility/commit/b5e7b0de4fa9eb6a6c076f1120e5f92a77b7679d
      path: flutter_keyboard_visibility
```

**Comment by hiteshsarsava** [comment]
Thanks. But I did fork and solved it.

**Comment by mofogasy** [comment]
We also need this!

**Comment by DrBu7cher** [comment]
Hey @mofogasy,
as I wrote [above](https://github.com/MisterJimson/flutter_keyboard_visibility/issues/141#issuecomment-1667335536), there is a solution to this problem. The latest official version of flutter_keyboard_visibility is 5.4.1, but 5.4.3 was released before, containing the fix to this. So I suggest you wait for the next release and meanwhile add the dependency as an override to your pubspec.yaml, as I described - as a ref to a git commit with the fix in it.
Best!

**Comment by mofogasy** [comment]
Hello @DrBu7cher,
Thank you for your reply. Unfortunately, dependency overrides are not an option in our project, so we're waiting for the next version to be published.
Cheers

**Comment by DrBu7cher** [comment]
I'm interested in why overrides are not an option :D

**Comment by Lee-Yoonjoo** [comment]
> https://github.com/MisterJimson/flutter_keyboard_visibility/blob/master/flutter_keyboard_visibility/android/build.gradle#L26 It's fixed since 3 months, but something broke [#131 (comment)](https://github.com/MisterJimson/flutter_keyboard_visibility/pull/131#issuecomment-1555118363) so it got reverted. [#132 (comment)](https://github.com/MisterJimson/flutter_keyboard_visibility/issues/132#issuecomment-1555915501) And the fix did not show up in pub.dev/was retracted. [#133 (comment)](https://github.com/MisterJimson/flutter_keyboard_visibility/pull/133#issuecomment-1576479483) So I suggest you add the following to your pubspec.yaml:
> 
> ```yaml
> dependency_overrides:
>   flutter_keyboard_visibility:
>     git:
>       url: https://github.com/MisterJimson/flutter_keyboard_visibility.git
>       ref: b5e7b0de4fa9eb6a6c076f1120e5f92a77b7679d # https://github.com/MisterJimson/flutter_keyboard_visibility/commit/b5e7b0de4fa9eb6a6c076f1120e5f92a77b7679d
>       path: flutter_keyboard_visibility
> ```
> 
> EDIT: Only until the new version is released of course. EDIT2: Here is the retracted version: https://pub.dev/packages/flutter_keyboard_visibility/versions/5.4.3

This solution cannot be applied. Because 5.4.3 has been RETRACTED. Is there any update about it?

**Comment by DrBu7cher** [comment]
It can be applied, because it does not use the retracted version.
The link to this version is only to show that it is not there anymore, but has been there, so there was an attempt to fix this problem.
The code with `dependency_overrides` is a direct reference to the code as it has been, when the retracted version has been created.
So you can use the snippet in you pubspec.yaml/add it to the other `dependency_overrides` in your pubspec.yaml if they exist and you are good to go.

**Comment by Lee-Yoonjoo** [comment]
@DrBu7cher 
It works with this specific commit. But sadly, my other library is not compatible either...^^ I am just holding the update.
`dependency_overrides:
  flutter_keyboard_visibility:
      git:
        url: https://github.com/MisterJimson/flutter_keyboard_visibility.git
        path: flutter_keyboard_visibility
        ref: e1f274729458cbddb92b1e4d78735c35dd63d02a`

**Comment by TheFabbiusCorp** [comment]
This commit is also fine. It's the latest on `master` as of today (2023/11/30).
```YAML
dependency_overrides:
  flutter_keyboard_visibility:
      git:
        url: https://github.com/MisterJimson/flutter_keyboard_visibility.git
        path: flutter_keyboard_visibility
        ref: 8c28373
```

**Comment by kkoskenvirta** [comment]
Would it be possible to get a new release to pub.dev with this fix included?

**Comment by MisterJimson** [comment]
Hey everyone. I'm going to push master as a new major version today. I was wary since when I tried to fix this last time it broke for everyone on Gradle 7. Thanks for the patience as I haven't been working on this library recently.

**Comment by MisterJimson** [comment]
`6.0.0-beta` is now out, it's 5.4.3 republished as a new major version. The Android Gradle changes were breaking for some users so 5.4.3 was unpublished. Using this version may require you to update your Android Gradle version.

Please let me know how this version works for you and include if your project uses Gradle 7 or 8.

**Comment by MisterJimson** [comment]
I had positive feedback on the beta so 6.0.0 is live.
