### ISSUE TITLE
Using the latest version of the plugin on pub.dev doesn't support flutter 3.16

### ISSUE THREAD

**Issue by ellet0** [MisterJimson/flutter_keyboard_visibility#147]
Using the latest version of the plugin on pub.dev which is `flutter_keyboard_visibility: ^5.4.1`
 doesn't support flutter 3.16

I tried to fork the repo and try it out myself but it managed to work, so maybe the maintainers of the package need to publish the new version?

**Comment by MisterJimson** [comment]
I've just tested 6.0.0-beta on a fresh counter app created with Flutter 3.16.4. Can you see if that works for you and if so I will publish it as a stable version.

**Comment by MisterJimson** [comment]
I had positive feedback on the beta so 6.0.0 is live.
