### ISSUE TITLE
Supporting the new Android plugins APIs

### ISSUE THREAD

**Issue by darwin-morocho** [MisterJimson/flutter_keyboard_visibility#16]
When I am creating a custom platform channel I can see that this plugin doesn't support Supporting the new Android plugins APIs. And the app crash.

https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

**Comment by MisterJimson** [comment]
I have this done on a 3.0.0 branch. Would you like to test it and see if it fixes the problem for you?

See here #15

**Comment by g-balas** [comment]
Using 3.0.0 branch with new Android plugins APIs is working for me as expected on my OnePlus6 (Android 10)

**Comment by savy-91** [comment]
Hi! I've been testing the branch 3.0.0 for a couple of days and I wanted to let you know that it breaks another plugin: flutter_workmanager.

I have been using flutter_workmanager for a while with discrete success, however when I added flutter_keyboard_visibility 3.0.0, I now get this error:
```W/FlutterEngine( 7509): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@4714453) but could not find and invoke the GeneratedPluginRegistrant```

**Comment by MisterJimson** [comment]
Now on pub: https://pub.dev/packages/flutter_keyboard_visibility
