### ISSUE TITLE
remove listen

### ISSUE THREAD

**Issue by taozhipeng1990** [MisterJimson/flutter_keyboard_visibility#17]
![image](https://user-images.githubusercontent.com/3894069/83377987-e6ad4f00-a409-11ea-8e21-17ceffd112d7.png)

**Comment by taozhipeng1990** [comment]
dispose  listen?

**Comment by MisterJimson** [comment]
You can put an `if (mounted)` check before the setState call.

KeyboardVisibility stays alive for the duration of the app, so you do not dispose it.

**Comment by taozhipeng1990** [comment]
I am a novice. Please forgive my ignorance.
I found a new method
`
	void initState() {
		super.initState();
		keyBoard = KeyboardVisibility.onChange.listen((bool visible) {
			setState(() {
				offset = visible?350:0;
			});
		});
	}

	@override
	void dispose() {
    	keyBoard?.cancel();
		super.dispose();
	}
`

**Comment by omidraha** [comment]
https://github.com/MisterJimson/flutter_keyboard_visibility/issues/50#issuecomment-790652594
