### ISSUE TITLE
onChange no longer emiting values in 3.0.0

### ISSUE THREAD

**Issue by TNorbury** [MisterJimson/flutter_keyboard_visibility#18]
Currently running Flutter 1.17.2, on a Pixel 2.

Upon upgrading to version 3.0.0, the onChange function no longer emits values

This is the code I'm running (_clearFocus is just a function that clears the focus from text fields) :
```
KeyboardVisibility.onChange.listen((isVisible) {
      if (!isVisible) {
        _clearFocus();
      }
    });
```

**Comment by MisterJimson** [comment]
Hmm strange. Does the example work for you on that device?

**Comment by TNorbury** [comment]
Hm, yeah, just tried the example and it seems to work. Maybe it's something in how I have the android part of my app configured...

The only difference I noticed right off hand was in my MainActivity.java, I override the onCreate method like so (whereas the example doesn't):
```java
 @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
```
I can't remember ever explicitly writing that code, but I did start this project awhile ago, so perhaps it's just an artifact of an older version of flutter. I try removing it and see if that works.

**Comment by MisterJimson** [comment]
Sounds good, let me know. 

This may be useful to you: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

Also note that you can delete your android or ios folders and recreate as Flutter default by running `flutter create .` in your project folder.

**Comment by TNorbury** [comment]
Yep, turns out my android stuff just needed an upgrade. Deleting the android folder and recreating the flutter project did the trick, thank you!
