### ISSUE TITLE
Android: Broken version 3.0.0, works in 0.7.0

### ISSUE THREAD

**Issue by ollydixon** [MisterJimson/flutter_keyboard_visibility#19]
I decided to update this library after awhile.
Currently broken on all our android devices (total 3) and I tested two emulators.
We revered back to 0.7.0 and everything is working again.

[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-NO)
    • Flutter version 1.17.3 at /Users/olly/flutter
    • Framework revision b041144f83 (3 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/olly/Library/Android/sdk
    • Platform android-R, build-tools 29.0.3
    • ANDROID_HOME = /Users/olly/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/olly/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

**Comment by matthew-carroll** [comment]
@ollydixon can you list the Android API versions that you tested on?

I just tried the demo app on a Pixel 3a running Android 10 and I'm correctly being notified when the keyboard appears and disappears.

Also, can you clarify whether or not the demo app fails in your devices? Or, if it requires a different UI to fail, can you post a minimal reproduction that shows the bug?

**Comment by ollydixon** [comment]
@matthew-carroll I just tested again on Android 29, OnePlus 6. Works with 0.7.0 but not 3.0.0

**Comment by MisterJimson** [comment]
I just started a branch to investigate this `old_android` and I was able to reproduce.

I have migrated the project to Android X and updated gradle but it is still reproducible, so I suspect its related to pre Flutter 1.12 created Android projects.

I will see if we can support both pre and post 1.12 Android projects. If not you can always migrate your Android project now.

https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by MisterJimson** [comment]
Looks like the `ActivityAware` callbacks don't trigger in pre 1.12 Android projects.

**Comment by MisterJimson** [comment]
I have opened this issue as it is not clear if ActivityAware should be working or not. https://github.com/flutter/flutter/issues/59556

**Comment by matthew-carroll** [comment]
I'm the one who implemented `ActivityAware`. It's part of a major refactor to how Android plugins work. This refactor is known as "v2" of the Android embedding.

"v1" of the Android embedding has no concept of `ActivityAware`, nor any concept of the `FlutterPlugin` class. The key to getting a plugin to work for the "v1" embedding is to correctly implement the `registerWith()` method. That method is from "v1".

By glancing at the code in this repo, here is what the method currently looks like:

```
public static void registerWith(PluginRegistry.Registrar registrar) {
    final FlutterKeyboardVisibilityPlugin plugin = new FlutterKeyboardVisibilityPlugin();
    plugin.init(registrar.messenger());
}
```

Here is what the method should probably look like:

```
public static void registerWith(PluginRegistry.Registrar registrar) {
    final FlutterKeyboardVisibilityPlugin plugin = new FlutterKeyboardVisibilityPlugin();
    plugin.init(registrar.messenger());
    plugin.onAttachedToActivity(registrar.activity());
}
```

In the case of the "v1" embedding, you must explicitly query the `registrar` for the artifacts that you need. There are no hook methods in "v1".

All the methods like `onAttachedToEngine()`, `onDetachedFromEngine()`, `onAttachedToActivity()`, and `onDetachedFromActivity()` are all exclusively "v2" methods. They will never be invoked if your project is using an earlier version of Flutter.

**Comment by MisterJimson** [comment]
Great, seems like an easy fix then.

**Comment by MisterJimson** [comment]
3.1.0 is out on pub with this fixed.
