### ISSUE TITLE
Consider eliminating public static references

### ISSUE THREAD

**Issue by matthew-carroll** [MisterJimson/flutter_keyboard_visibility#21]
I just submitted a PR with some new functionality for this package. In the process of extending this package and attempting to write tests, I noticed that this package relies on static members to query and notify clients of keyboard changes.

I would like to suggest migrating away from public static members.

Static members often interfere with testing practices. This is especially true for plugins where a connection is expected with the platform side. Such a connection is not easily faked.

In my PR I introduced a pretty ugly hack to facilitate a few simple tests. This was the result of those public static members.

An alternative to public static members is to provide only a singleton reference at the static level. For example:

```
final KeyboardVisibility keyboardVisibility = KeyboardVisibility.instance;
print('Is visible: ${keyboardVisibility.isVisible}');
```

With a singleton instance, one can replace the entire instance with a fake instance within tests. This avoids polluting the primary API surface with methods that should only be invoked during tests. It also lowers the likelihood that someone will inadvertently invoke a test method during production.

You can see this practice within Flutter if you look at bindings, for example:

```
WidgetsBinding.instance;
ServicesBinding.instance;
```

**Comment by tuononh** [comment]
Does this package even works? I just tried latest version 3.0.0 and it is not working on Android ☹️

**Comment by matthew-carroll** [comment]
@tuononh looks like that issue is discussed here: https://github.com/MisterJimson/flutter_keyboard_visibility/issues/19
