### ISSUE TITLE
Consider adding tests for KeyboardVisibility

### ISSUE THREAD

**Issue by matthew-carroll** [MisterJimson/flutter_keyboard_visibility#22]
The `KeyboardVisibility` class is quite simple, but it wouldn't hurt to lock it down with some tests.

Adding tests for `KeyboardVisibility` would expose some of the fundamental testing issues that I ran into in my recent PR for this library. It would also provide piece of mind for future contributions to ensure that nothing breaks.

To the extent possible, you might also consider adding tests on the platform side to ensure that the per-platform code queries the right platform APIs. This might be accomplished with Espresso tests or Robolectric tests for Android, and EarlGray tests for iOS.

**Comment by MisterJimson** [comment]
Fairly happen with test converge progress. More to do but much better than when this was opened!
