### ISSUE TITLE
Verify Android keyboard detection logic

### ISSUE THREAD

**Issue by matthew-carroll** [MisterJimson/flutter_keyboard_visibility#23]
Looking at the current logic used in the Android code to detect keyboard appearance, it's based entirely on window dimensions. However, the following doc seems to suggest that one should also check the status of the `InputMethodManager`. The window dimensions alone may not be sufficient.

https://developer.salesforce.com/docs/atlas.en-us.noversion.service_sdk_android.meta/service_sdk_android/android_detecting_keyboard.htm

**Comment by MisterJimson** [comment]
Seems like something that is worth looking into

**Comment by MisterJimson** [comment]
This would be the ideal check if it makes it into an AndroidX lib: https://www.reddit.com/r/androiddev/comments/f6zs5b/finally_android_r_has_api_to_check_if_keyboard_is/

**Comment by MisterJimson** [comment]
This could be a much better solution: https://twitter.com/chrisbanes/status/1296164894199382025

**Comment by MisterJimson** [comment]
`4.0.4-beta.0` is available with a new Android implementation using the fairly new WindowInsetsCompat features.

Any feedback is appreciated before I merge this into a main version.

**Comment by MisterJimson** [comment]
Closed in 4.0.4.
