### ISSUE TITLE
Do I need to do anything in dispose() ?

### ISSUE THREAD

**Issue by sec7et** [MisterJimson/flutter_keyboard_visibility#30]
@override
  void initState() {
    super.initState();
    _keyboardState = KeyboardVisibility.isVisible;
    KeyboardVisibility.onChange.listen((bool visible) {
      debugPrint("test test");
      setState(() {
        _keyboardState = visible;
      });
    });
  }

This is my code. Should I do something in dispose() when I leave current page?

Because I receive some wrong message in DEBUG CONSOLE.

[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _BindBankCardPageState#e57ee(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets<…>

**Comment by limouren** [comment]
`KeyboardVisibility.onChange.listen` returns a `StreamSubscription`. You can keep it as an instance variable and call `cancel()` in your dispose.

**Comment by sec7et** [comment]
> `KeyboardVisibility.onChange.listen` returns a `StreamSubscription`. You can keep it as an instance variable and call `cancel()` in your dispose.

Ok~Copy that~Thank you~

**Comment by MisterJimson** [comment]
`KeyboardVisibility.onChange` is the direct query. It only is created once and is designed to be alive for the lifetime of your app.

If you are setting state in a callback from it, you may need to do `if (mounted)` before than so you don't call setState after dispose.

There is also `KeyboardVisibilityProvider` if you want to use it in your widget tree directly.
