### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by megageorge93** [MisterJimson/flutter_keyboard_visibility#38]
https://pastebin.com/Feir5vCU
Throwing an error

MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility)

**Comment by MisterJimson** [comment]
If you are getting a MissingPluginException, it may mean your platform project is not configured correctly.

**Comment by kiaxseventh** [comment]
```
════════ Exception caught by services library ══════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel flutter_keyboard_visibility:
MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility)


```
same issue

**Comment by MisterJimson** [comment]
Does the example in this repo work for you? Can you provide a reproduction example?

**Comment by MisterJimson** [comment]
Unfortunately this seems like a project setup issue, not an issue with the library. Reopen if you can provide a reproducible sample.
