### ISSUE TITLE
error: package androidx.annotation does not exist

### ISSUE THREAD

**Issue by chrystoffer** [MisterJimson/flutter_keyboard_visibility#40]
> Building plugin flutter_keyboard_visibility...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    7,3s
/Users/ids/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/android/src/main/java/com/jrai/flutter_keyboard_visibility/FlutterKeyboardVisibilityPlugin.java:9: error: package androidx.annotation does not exist
import androidx.annotation.NonNull;
/Users/ids/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/android/src/main/java/com/jrai/flutter_keyboard_visibility/FlutterKeyboardVisibilityPlugin.java:25: error: cannot find symbol
  public void onAttachedToEngine(@NonNull FlutterPluginBinding flutterPluginBinding) {
  symbol:   class NonNull
  location: class FlutterKeyboardVisibilityPlugin
/Users/ids/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/android/src/main/java/com/jrai/flutter_keyboard_visibility/FlutterKeyboardVisibilityPlugin.java:50: error: cannot find symbol
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
  symbol:   class NonNull
  location: class FlutterKeyboardVisibilityPlugin
/Users/ids/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/android/src/main/java/com/jrai/flutter_keyboard_visibility/FlutterKeyboardVisibilityPlugin.java:55: error: cannot find symbol
  public void onAttachedToActivity(@NonNull ActivityPluginBinding binding) {
  symbol:   class NonNull
  location: class FlutterKeyboardVisibilityPlugin
/Users/ids/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-3.2.2/android/src/main/java/com/jrai/flutter_keyboard_visibility/FlutterKeyboardVisibilityPlugin.java:65: error: cannot find symbol
  public void onReattachedToActivityForConfigChanges(@NonNull ActivityPluginBinding binding) {
  symbol:   class NonNull
  location: class FlutterKeyboardVisibilityPlugin
5 errors
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Get more help at https://help.gradle.org
BUILD FAILED in 6s
The plugin flutter_keyboard_visibility could not be built due to the issue above.

Does anyone know how I can fix?

**Comment by MisterJimson** [comment]
Perhaps you need to enable Android X? https://flutter.dev/docs/development/androidx-migration

**Comment by MisterJimson** [comment]
Unfortunately this seems like a project setup issue, not an issue with the library. Reopen if you can provide a reproducible sample.
