### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by ReniDelonzek** [MisterJimson/flutter_keyboard_visibility#41]
While compiling app, I am get this message about:

flutter_keyboard_visibility-3.2.2/android/src/main/java/com/jrai/flutter_keyboard_visibility/FlutterKeyboardVisibilityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by MisterJimson** [comment]
Yes, that is to maintain compatibility with Android Flutter projects created before v1.12.

We will drop this in the next major release, as the official plugins have as well.
