### ISSUE TITLE
Testing guide

### ISSUE THREAD

**Issue by IlyaMax** [MisterJimson/flutter_keyboard_visibility#45]
Why did you make your KeyboardVisibility class with static methods? It would be useful to mock onChange stream and isVisible getter instead of calling setVisibility.

**Comment by MisterJimson** [comment]
Thanks for the feedback. Like you mentioned, currently you can call `setVisibilityForTesting`.

Moving away from statics is covered here: #21.

I am working on a new major version with support for federation. I'll consider seeing if we can close #21 as part of it.
