### ISSUE TITLE
Keyboard visibility not detected on ios version 13.5.1 (iPhone 6s)

### ISSUE THREAD

**Issue by jorg1piano** [MisterJimson/flutter_keyboard_visibility#46]
As the title suggests. It does not seem to register when the soft keyboard is extended on my old iPhone 6s.

Tested the same code on Android and it worked fine there, so it doesn't seem to be an issue with the code.

Tested it with a KeyboardVisibilityBuilder like in the example.

**Comment by MisterJimson** [comment]
Hmm. Does the example app work if you run it on that phone?

**Comment by MisterJimson** [comment]
No follow up on example app usage so closing for now.
