### ISSUE TITLE
The method 'listen' isn't defined for the type 'KeyboardVisibilityController'.

### ISSUE THREAD

**Issue by ranajit1996** [MisterJimson/flutter_keyboard_visibility#48]
Can't listen to Keyboard Visibility as demonstrated in the documentation. Getting error.

**Comment by MisterJimson** [comment]
Can you provide a code sample? Are you creating an instance of KeyboardVisibilityController?

**Comment by ranajit1996** [comment]
Following code is not working:

```
import 'package:flutter_keyboard_visibility/flutter_keyboard_visibility.dart';

@override
void initState() {
  super.initState();

  var keyboardVisibilityController = KeyboardVisibilityController();
  // Query
  print('Keyboard visibility direct query: ${keyboardVisibilityController.isVisible}');
  
  // Subscribe
  keyboardVisibilityController.listen((bool visible) {
    print('Keyboard visibility update. Is visible: ${visible}');
  });
```

Please have a look on the attached image:
![Screenshot (109)](https://user-images.githubusercontent.com/62388874/100135259-672ba480-2eaf-11eb-9f40-dfd0c855da2a.png)

**Comment by MisterJimson** [comment]
AH my bad! Sorry. The stream property is `onChange` and you call listen on that.

`keyboardVisibilityController.onChange.listen`

Ill update the readme
