### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by maximletushov** [MisterJimson/flutter_keyboard_visibility#49]
Hi,
Flutter team announced that sound null safety is available in beta. https://medium.com/flutter/announcing-dart-null-safety-beta-4491da22077a
Please consider to prepare this library to null safety in advance. Thank you!

**Comment by MisterJimson** [comment]
A preview release is available as `5.0.0-nullsafety.0` and you can also view the code here: https://github.com/MisterJimson/flutter_keyboard_visibility/tree/null-safety

This won’t be merged to master and published as stable release until the Flutter team recommends we do that.

**Comment by maximletushov** [comment]
@MisterJimson thanks a lot 👍
