### ISSUE TITLE
Removable listener

### ISSUE THREAD

**Issue by bobs4462** [MisterJimson/flutter_keyboard_visibility#50]
Please add possibility to remove listeners added via onChange.listen method.
Reason: if we pass a closure to listen, which references some variables of widget, then after widget is disposed, the closure keeps firing on visibility change, and it tries to access variable which are long gone.

**Comment by MisterJimson** [comment]
I will look into this, but as a whole I recommend the new Widgets the library provides rather than using onChange directly.

**Comment by bobs4462** [comment]
Thanks

**Comment by MisterJimson** [comment]
Sorry for the late response. If you are using the `onChange` stream, calling `listen` returns a `StreamSubscription` that can be cancelled.

Here is a sample:
```dart
  final _keyboardVisibilityController = KeyboardVisibilityController();
  StreamSubscription? onChangeSub;

  @override
  void initState() {
    onChangeSub = _keyboardVisibilityController.onChange.listen((isVisible) {
      print('The keyboard is: ${isVisible ? 'VISIBLE' : 'NOT VISIBLE'}');
    });
    super.initState();
  }

  @override
  void dispose() {
    onChangeSub?.cancel();
    super.dispose();
  }
```
