### ISSUE TITLE
[!] No podspec found for `flutter_keyboard_visibility_web` in `.symlinks/plugins/flutter_keyboard_visibility_web/ios`

### ISSUE THREAD

**Issue by sec7et** [MisterJimson/flutter_keyboard_visibility#52]
flutter_keyboard_visibility: ^4.0.2

When I execute "pod install" in the ios directory, this is log:
pod install
Analyzing dependencies
[!] No podspec found for `flutter_keyboard_visibility_web` in `.symlinks/plugins/flutter_keyboard_visibility_web/ios`

How can I fix the problem? Thanks.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H15, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)

pod --version
1.9.3

**Comment by pslxx** [comment]
me too

**Comment by MisterJimson** [comment]
Hmm that is strange. I am not able to reproduce. The web package is obviously not supported to be integrated to the iOS project. For me I don’t see `_web` in the `Podfile.lock` or in `ios/symlinks/plugins`.

Can you try deleting your `Podfile.lock` and running `pod repo update`, `pod install`.

If that doesn’t work, you can try updating cocoapods as well, I am on version 10.

**Comment by sec7et** [comment]
> Hmm that is strange. I am not able to reproduce. The web package is obviously not supported to be integrated to the iOS project. For me I don’t see `_web` in the `Podfile.lock` or in `ios/symlinks/plugins`.
> 
> Can you try deleting your `Podfile.lock` and running `pod repo update`, `pod install`.
> 
> If that doesn’t work, you can try updating cocoapods as well, I am on version 10.

ok, I will try it later. Thanks

**Comment by kiz0** [comment]
When

> Hmm that is strange. I am not able to reproduce. The web package is obviously not supported to be integrated to the iOS project. For me I don’t see `_web` in the `Podfile.lock` or in `ios/symlinks/plugins`.
> 
> Can you try deleting your `Podfile.lock` and running `pod repo update`, `pod install`.
> 
> If that doesn’t work, you can try updating cocoapods as well, I am on version 10.

When I try `pod install`

```
Analyzing dependencies
[!] No podspec found for `flutter_keyboard_visibility_web` in `.symlinks/plugins/flutter_keyboard_visibility_web/iOS`
```

**Comment by sec7et** [comment]
> > Hmm that is strange. I am not able to reproduce. The web package is obviously not supported to be integrated to the iOS project. For me I don’t see `_web` in the `Podfile.lock` or in `ios/symlinks/plugins`.
> > Can you try deleting your `Podfile.lock` and running `pod repo update`, `pod install`.
> > If that doesn’t work, you can try updating cocoapods as well, I am on version 10.
> 
> ok, I will try it later. Thanks

I tried remove `Podfile.lock` and `pod repo update`, now my pod version is 1.10.0, but it's still the same error.
My step is:
`flutter clean`
`flutter pub get`
cd ios
`pod install`
It's not work for me. 😂

**Comment by MisterJimson** [comment]
Does the example app work for you? And if it does, is there a way I can get a reproducible sample project?

**Comment by MisterJimson** [comment]
Ah I figured it out! It id reproducible in the `example_old` project in this repo.

That means your iOS `Podfile` (not the Podfile.lock) is out of date. Flutter changed the structure of the iOS `Podfile` a while back.

So to fix it, delete your `Podfile` and `Podfile.lock`, then just try to run your app. Flutter will detect that it is missing and recreate it.

Note that if you had any custom changes in the Podfile you will need to put them back in the new version of the file.

You can compare the samples in this repo to see the difference:

New: https://github.com/MisterJimson/flutter_keyboard_visibility/blob/master/flutter_keyboard_visibility/example/ios/Podfile
Old: https://github.com/MisterJimson/flutter_keyboard_visibility/blob/master/flutter_keyboard_visibility/example_old/ios/Podfile

**Comment by sec7et** [comment]
> Ah I figured it out! It is reproducible in the `example_old` project in this repo.
> 
> That means your iOS `Podfile` (not the Podfile.lock) is out of date. Flutter changed the structure of the iOS `Podfile` a while back.
> 
> So to fix it, delete your `Podfile` and `Podfile.lock`, then just try to run your app. Flutter will detect that it is missing and recreate it.
> 
> Note that if you had any custom changes in the Podfile you will need to put them back in the new version of the file.
> 
> You can compare the samples in this repo to see the difference:
> 
> New: https://github.com/MisterJimson/flutter_keyboard_visibility/blob/master/flutter_keyboard_visibility/example/ios/Podfile
> Old: https://github.com/MisterJimson/flutter_keyboard_visibility/blob/master/flutter_keyboard_visibility/example_old/ios/Podfile

Ah you are right! My project was created by Flutter 1.12.8. I often see the console log: rm Podfile. But I never deal with the problem. Well, that should be the problem, I will try it. Thank you for giving me such a detailed answer. 👍

**Comment by mrpawle** [comment]
> Ah I figured it out! It is reproducible in the `example_old` project in this repo.
> 
> That means your iOS `Podfile` (not the Podfile.lock) is out of date. Flutter changed the structure of the iOS `Podfile` a while back.
> 
> So to fix it, delete your `Podfile` and `Podfile.lock`, then just try to run your app. Flutter will detect that it is missing and recreate it.
> 
> Note that if you had any custom changes in the Podfile you will need to put them back in the new version of the file.
> 
> You can compare the samples in this repo to see the difference:
> 
> New: https://github.com/MisterJimson/flutter_keyboard_visibility/blob/master/flutter_keyboard_visibility/example/ios/Podfile
> Old: https://github.com/MisterJimson/flutter_keyboard_visibility/blob/master/flutter_keyboard_visibility/example_old/ios/Podfile

It's worked. Thanks

**Comment by flutter-painter** [comment]
Only way out for me was to create a macos folder and then to put the attached file with .podspec extension
In case this might help

[flutter_keyboard_visibility.txt](https://github.com/MisterJimson/flutter_keyboard_visibility/files/10377566/flutter_keyboard_visibility.txt)

**Comment by flutter-painter** [comment]
putting the actual file content for archive,
also name needs to be flutter_keyboard_visibility_macos.podspec

```
Pod::Spec.new do |s|
  s.name             = 'flutter_keyboard_visibility_macos'
  s.version          = '0.0.1'
  s.summary          = 'flutter_keyboard_visibility_macos'
  s.description      = <<-DESC
Flutter keyboard visibility
                       DESC
  s.homepage         = 'https://github.com/MisterJimson/flutter_keyboard_visibility_macos'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Jason Rai' => 'jason.c.rai@gmail.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.public_header_files = 'Classes/**/*.h'
  s.dependency 'FlutterMacOS'

  s.platform = :osx, '10.11'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
  s.swift_version = '5.0'
end
```
