### ISSUE TITLE
flutter_keyboard_visibility bug in ios

### ISSUE THREAD

**Issue by blue492** [MisterJimson/flutter_keyboard_visibility#54]
Iam using Flutter in Mac -> Android studio and when I write pod install in the terminal. It show me

  ```
  Analyzing dependencies
[!] No podspec found for `flutter_keyboard_visibility_web` in .symlinks/plugins/flutter_keyboard_visibility_web/ios`

  ```
flutter_typeahead plugin has a Dependencies with flutter_keyboard_visibility 

Iam using flutter from one year ago, It is the first time it happen for me. 
I cannot run the app. I don't have a plugin with this name flutter_keyboard_visibility_web in pubspec

How to fix it, thanks
@MisterJimson

**Comment by MisterJimson** [comment]
Your iOS Podfile is out of date.

See here: https://github.com/MisterJimson/flutter_keyboard_visibility/issues/52
