### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility)

### ISSUE THREAD

**Issue by kamleshwebtech** [MisterJimson/flutter_keyboard_visibility#56]
Getting error - MissingPluginException(No implementation found for method listen on channel flutter_keyboard_visibility)

**Comment by MisterJimson** [comment]
This typically means your Android or iOS projects are not setup properly.

Does the issue happen if you try the example project?

**Comment by woelmer** [comment]
I got this error after adding the plugin and hot restarting my app. I fixed it by completely stopping the app and restarting.

**Comment by MisterJimson** [comment]
@woelmer Yeah another great case. Anytime native code is changed or added you will need a full recompile.

**Comment by MisterJimson** [comment]
Without more info for a direct action, I will be closing this.
