### ISSUE TITLE
FlutterKeyboardVisibilityPlugin cannot find symbol Type on line 91

### ISSUE THREAD

**Issue by anchals333** [MisterJimson/flutter_keyboard_visibility#60]
Hi, I am getting this error when building an apk. Complete log :
```

flutter_keyboard_visibility-4.0.4\android\src\main\java\com\jrai\flutter_keyboard_visibili
ty\FlutterKeyboardVisibilityPlugin.java:91: error: cannot find symbol
        isVisible = insets.isVisible(WindowInsetsCompat.Type.ime());
                                                       ^
  symbol:   variable Type
  location: class WindowInsetsCompat
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_keyboard_visibility:compileReleaseJavaWithJavac'.
```
I have **flutter version 1.22.5**.

**Comment by MisterJimson** [comment]
Hmm thats interesting. Are you using proguard or any minification in release builds?

**Comment by anchals333** [comment]
Yes but even the debug build is breaking. I tried updating the flutter version, build tool version. Also, my compileSdkVersion 29 and in your example it is 28. Actually I am using a typehead plugin which internally using keyboard visibility plugin. And now it's breaking the build. From yesterday I am facing this issue.

**Comment by MisterJimson** [comment]
Same error for the debug build?

You can downgrade for now to 4.0.3 to fix the issue.

What version of typehead are you using?

**Comment by MisterJimson** [comment]
FYI I did some testing and was able to build both debug and release with flutter_keyboard_visibility version 4.0.4 with and without flutter_typeahead added as well.

Can you provide any other details to help reproduce? A sample project would be best.

**Comment by anchals333** [comment]
Hi, I downgraded to 4.0.3 & it works. But what I found is `flutter_typeahead: ^1.9.1` is using `flutter_keyboard_visibility: ^4.0.2` in his pubspec.yaml. So,  I don't know from where it upgraded to `flutter_keyboard_visibility: ^4.0.4`. In pubspec.lock file I manually changed 4.0.4 to 4.0.3 and it works. Thanks for quick response.

**Comment by MisterJimson** [comment]
Ok. FYI flutter_typeahead 2.0.0 worked for me with 4.0.4

**Comment by dileepvarmau** [comment]
I am also getting the same issue with the latest version. v4.0.3 working fine.

Execution failed for task ':flutter_keyboard_visibility:compileDebugJavaWithJavac'.
* What went wrong:
Launching lib/main_dev.dart on Android SDK built for x86 in debug mode...
lib/main_dev.dart:1
/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-4.0.6/android/src/main/java/com/jrai/flutter_keyboard_visibility/FlutterKeyboardVisibilityPlugin.java:91: error: cannot find symbol
        isVisible = insets.isVisible(WindowInsetsCompat.Type.ime());
                                                       ^
  symbol:   variable Type
  location: class WindowInsetsCompat
1 error

FAILURE: Build failed with an exception.

I am using flutter_typehead - v2.0.0 and 
I am on Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-IN)
    • Flutter version 1.22.6 at /Users/dileepvarma/Documents/SDKs/flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/dileepvarma/Library/Android/sdk
    • Platform android-30, build-tools 29.0.0
    • ANDROID_HOME = /Users/dileepvarma/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

**Comment by MisterJimson** [comment]
For anyone getting this I am looking for a reproducible sample to investigate it

**Comment by anchal-td** [comment]
This issue pops up again after upgrading to flutter 2.0. I have to upgrade it to 5.0.0 & not again getting the same issue. Not sure why, in an example project it is working fine but  in my current project it breaks with above issue.
