### ISSUE TITLE
onChange listener it's called twice

### ISSUE THREAD

**Issue by 0aps** [MisterJimson/flutter_keyboard_visibility#61]
**Describe the bug**
onChange listener it's called twice

**To Reproduce**
1. Create a StatefulWidget and subscribe directly to the listener on the initState
2. Add a single TextField 
3. Click on the input to display the keyboard
4. See the onChange callback it's called twice with the true state. Close the keyboard and see the onChange callback it's called twice with the false state. 

**Expected behavior**
The onChange callback should only be executed once (both for keyboard open and close)

**Info (please complete the following information):**
`flutter_keyboard_visibility` version: 4.0.4
Tested on Android Emulator with Flutter 1.22.6

 
**Additional context**
This bug doesn't happen on version 3.0.0. Callback behaves as expected.

**Comment by MisterJimson** [comment]
Should be fixed in the newest release

**Comment by 0aps** [comment]
working as expected now. Thanks!
