### ISSUE TITLE
Update plugin_platform_interface to 2.0.0

### ISSUE THREAD

**Issue by KurodaSayama** [MisterJimson/flutter_keyboard_visibility#63]
Other packages are already using plugin_platform_interface 2.0.0 for null-safety and I got a version solving error because this package is using 1.1.0-nullsafety.1. Would it be possible to update?

**Comment by MisterJimson** [comment]
flutter_keyboard_visibility_platform_interface 2.0.0
flutter_keyboard_visibility_web 2.0.0
flutter_keyboard_visibility 5.0.0

These have all be updated and released!
