### ISSUE TITLE
Deprecated API on Flutter 2

### ISSUE THREAD

**Issue by jerickdlee** [MisterJimson/flutter_keyboard_visibility#66]
Hello first of all thank you for this package.

I noticed the following warning whenever I attempt to build an apk:

`Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-5.0.0\android\src\main\java\com\jrai\flutter_keyboard_visibility\FlutterKeyboardVisibilityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.`

It is not causing any problems on my end but it seems to me that some dependencies need to be updated.

Thank you

**Comment by MisterJimson** [comment]
Hello! This is expected and required to support users on older versions of Flutter, or Flutter projects that haven’t updated the Android project structure: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

Will be removed at some point in the future.
