### ISSUE TITLE
Unexpected child "asserts" found under "flutter".

### ISSUE THREAD

**Issue by ron-don** [MisterJimson/flutter_keyboard_visibility#68]
Hi
I'Ve been forwarded here from GitHub, after having a a bug in my pubspec.yaml file when I run the app.
When I run 'flutter pub get', it runs okay without any errors.
The bug is somehow related to 'flutter_keyboard_visibility', coz that's the error I'm getting.
Please help!!!

[flutter doctor -v.txt](https://github.com/MisterJimson/flutter_keyboard_visibility/files/6302957/flutter.doctor.-v.txt)

[pubspec.txt](https://github.com/MisterJimson/flutter_keyboard_visibility/files/6302955/pubspec.txt)

<img width="1598" alt="Screenshot 2021-04-13 at 12 11 49" src="https://user-images.githubusercontent.com/38691932/114537114-7b9fec00-9c5a-11eb-9471-7d64a035e6cf.png">

**Comment by MisterJimson** [comment]
What version of flutter_keyboard_visibility are you using? Its not in the text file.

**Comment by ron-don** [comment]
Hi, Thanks for the reply. 
Sorry about that...
I've initially used the latest flutter_keyboard_visibility 5.0.0 and didn't work, hence now using this with no specific version.

**Comment by MisterJimson** [comment]
I have updated some Android dependancies, 5.0.1 may resolve this issue for you.

**Comment by MisterJimson** [comment]
Going to close, if you still have the issue on 5.0.1 please reopen with more information on how to reproduce.
