### ISSUE TITLE
flutter_keyboard_visibility: 5.0.2 won't compile for Android

### ISSUE THREAD

**Issue by ollydixon** [MisterJimson/flutter_keyboard_visibility#74]
When trying to compile for Android; we get the following issue.

```
/Users/me/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-5.0.2/android/src/main/java/com/jrai/flutter_keyboard_visibility/FlutterKeyboardVisibilityPlugin.java:91: error: cannot find symbol
        isVisible = insets.isVisible(WindowInsetsCompat.Type.ime());
                                                       ^

```

<img width="797" alt="Screenshot 2021-05-15 at 10 47 22" src="https://user-images.githubusercontent.com/6940726/118354458-7096ef00-b56b-11eb-8ae4-bbe71d857a48.png">

**Comment by ollydixon** [comment]
This fix is this.

```
  isVisible = isSystemKeyboardVisible(activity.getBaseContext());

  /**
   * Check system keyboard visibility
   * @return true if visible
   */
  public boolean isSystemKeyboardVisible(Context context) {
    try {
      final InputMethodManager manager = (InputMethodManager) context.getSystemService(Context.INPUT_METHOD_SERVICE);
      final Method windowHeightMethod = InputMethodManager.class.getMethod("getInputMethodWindowVisibleHeight");
      final int height = (int) windowHeightMethod.invoke(manager);
      return height > 0;
    } catch (Exception e) {
      return false;
    }
  }
```

If you could push this fix asap would be great; since it's blocking our build servers. :-)

**Comment by ollydixon** [comment]
@MisterJimson :-D

**Comment by MisterJimson** [comment]
@ollydixon You are welcome to point your `flutter_keyboard_visibility` dependancy to a git fork to resolve this without any external involvement. I would recommend this anytime you have an urgent issue, as you can never guarantee timely support from volunteer OSS projects.  

Here is an example of how to do that:
```
dependencies:
  flutter_keyboard_visibility:
    git:
      url: git@github.com:<githubOrgOrUser>/flutter_keyboard_visibility.git
      ref: <branchOrTag>
```

Regarding the bug. I would like to see a reproducible sample project. The current implementation uses WindowInsetsCompat, which is the modern way to check for insets like the keyboard, and I would rather not use a reflection based approach.

**Comment by ollydixon** [comment]
@MisterJimson hmm. Strange; any ideas why my project would fail then? Everything is updated, using latest Flutter ``2.0.6``?

**Comment by MisterJimson** [comment]
@ollydixon unsure without a sample. Do you use the `androidx.core:core` library in your app `build.gradle`?

It could be a conflict of versions.

**Comment by ollydixon** [comment]
@MisterJimson I will setup a basic project in a few days for you.

**Comment by ollydixon** [comment]
@MisterJimson to answer your question; yes update to AndroidX as it was required for a package.

**Comment by LeonFangCN** [comment]
I have the same problem.

**Comment by jackieoh1** [comment]
i am having the same issue.

**Comment by ollydixon** [comment]
@jackieoh1 I still didn't resolve it even removed all cache and redownloaded the packages. I had to manaully patch the Android project with my fix. I think he's using an older version of Android.

**Comment by jackieoh1** [comment]
> @jackieoh1 I still didn't resolve it even removed all cache and redownloaded the packages. I had to manaully patch the Android project with my fix. I think he's using an older version of Android on his projects is my guess.

I don't have the skill to do that, unfortunately.  thank you for the update.  this is not good.

**Comment by ollydixon** [comment]
@jackieoh1 just open the Flutter project in Android Studio you will see ```flutter_keyboard_visibility``` then you will see the file you need to patch it's easy.

**Comment by jackieoh1** [comment]
yes - i see the file - i just don't know where to add your code?  sorry for the continuing questions and thank you for your help.

**Comment by ollydixon** [comment]
@MisterJimson still seeing this issue along with some of my other developers; any chance in a fix?

**Comment by MisterJimson** [comment]
Can you try adding this to your main app dependancies? 

`implementation "androidx.core:core:1.5.0-rc01"`

**Comment by ollydixon** [comment]
@MisterJimson can confirm this fixed, upgraded from ```1.1.0``` which was default in project.

**Comment by ollydixon** [comment]
@MisterJimson this is happening with brand new flutter projects; perhaps it could be fixed? (I showed how)

**Comment by ollydixon** [comment]
@MisterJimson this fix no longer works for us on new Flutter project 🥲

**Comment by ollydixon** [comment]
@MisterJimson I have a fix here but what you recommended doesn't work.
https://github.com/ollydixon/flutter_keyboard_visibility

**Comment by ollydixon** [comment]
@MisterJimson 

> @ollydixon You are welcome to point your `flutter_keyboard_visibility` dependancy to a git fork to resolve this without any external involvement. I would recommend this anytime you have an urgent issue, as you can never guarantee timely support from volunteer OSS projects.
> 
> Here is an example of how to do that:
> 
> ```
> dependencies:
>   flutter_keyboard_visibility:
>     git:
>       url: git@github.com:<githubOrgOrUser>/flutter_keyboard_visibility.git
>       ref: <branchOrTag>
> ```
> 
> Regarding the bug. I would like to see a reproducible sample project. The current implementation uses WindowInsetsCompat, which is the modern way to check for insets like the keyboard, and I would rather not use a reflection based approach.

I have a fix below but you recommendation doesn't work.
https://github.com/ollydixon/flutter_keyboard_visibility

```pub get failed (1; Could not find a file named "pubspec.yaml" in git@github.com:ollydixon/flutter_keyboard_visibility.git cc68ca71453a2fa6dc12fe6d805b4d2ea7eb154f.)```

**Comment by ollydixon** [comment]
Even trying the following breaks

```
flutter_keyboard_visibility:
    git: 
      url: git://github.com/ollydixon/flutter_keyboard_visibility/flutter_keyboard_visibility
      ref: master
```

Not sure what to do now.

**Comment by ollydixon** [comment]
@MisterJimson there are now multiple issues, including issues with the new Gradle etc.

I've made a fix here https://github.com/ollydixon/flutter_keyboard_visibility

anyone who is reading wants to implement this; please use the following:
```
  flutter_keyboard_visibility:
    git: 
      url: git://github.com/ollydixon/flutter_keyboard_visibility
      ref: master
      path: flutter_keyboard_visibility
```

**Comment by MisterJimson** [comment]
I've decided to remove AndroidX as it added too many problems like this. I've reverted to an old way of checking in 5.0.3

**Comment by ollydixon** [comment]
@MisterJimson yeah makes sense. I hate that Google basically screwed up the whole Android ecosystem just to change some package names

**Comment by ollydixon** [comment]
<img width="1517" alt="Screenshot 2021-07-21 at 13 23 20" src="https://user-images.githubusercontent.com/6940726/126481193-5861297c-733e-4990-9406-3a4f591d9577.png">

**Comment by ollydixon** [comment]
@MisterJimson seems the update now breaks the build steps.

**Comment by MisterJimson** [comment]
@ollydixon you can use whatever version of gradle or gradle wrapper works best for your project. You can see that the error points to your private gradle path, not a path to the project itself.

**Comment by ollydixon** [comment]
@MisterJimson this is a new project and your package is failing, only your package; what did you change?

**Comment by MisterJimson** [comment]
You can see here: https://github.com/MisterJimson/flutter_keyboard_visibility/issues/77

Did you try the suggestion in the error message? Does the example project in this repo work for you?

**Comment by ollydixon** [comment]
@MisterJimson this is from a fresh Flutter project; it's not compatible with it. If it doesn't work with standard Flutter projects there's a configuration issue with the library; perhaps you bumped the gradle version by accident?

**Comment by MisterJimson** [comment]
Unfortunately there are many different things on each person machine that can effect what can be built. Different paths, gradle versions, etc.

If you can answer the 2 questions I left above and still have the problem, the next step would be to provide a reproducible sample project.
