### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by sgehrman** [MisterJimson/flutter_keyboard_visibility#75]
final keyboardVisibilityController = KeyboardVisibilityController();
      final bool keyboardVisible = keyboardVisibilityController.isVisible;

      print('keyboardVisible');
      print(keyboardVisible);

Keyboard is visible, but it returns false.  I'm on Android.  Latest version.

**Comment by MisterJimson** [comment]
Does the sample app work for you?

**Comment by nilsreichardt** [comment]
Is it working after rebuilding the app?

**Comment by MisterJimson** [comment]
Without more information I am unable to help
