### ISSUE TITLE
Only works second time keyboard is shown

### ISSUE THREAD

**Issue by sgehrman** [MisterJimson/flutter_keyboard_visibility#76]
KeyboardVisibilityBuilder(
            builder: (context, isKeyboardVisible) {

I show the keyboard the first time.  Trigger this view, it returns 'false'.  Continues to show false until I hide and reshow the keyboard.

**Comment by sgehrman** [comment]
I'm on Android if that matters.

**Comment by sgehrman** [comment]
this works better: 

if (MediaQuery.of(context).viewInsets.bottom != 0) 
    print('keyboard visible');

**Comment by MisterJimson** [comment]
Does this happen in the sample project in this repo? What version of the lib are you using?

**Comment by MisterJimson** [comment]
Please reopen with reproduction steps and a sample project if this is still happening. Unable to reproduce.
