### ISSUE TITLE
onChange.listen can not dispose

### ISSUE THREAD

**Issue by WXXXXH** [MisterJimson/flutter_keyboard_visibility#79]
onChange.listen can not dispose
after onChange.listen more and more

**Comment by MisterJimson** [comment]
Can you add more detail or a reproducible sample?

You may want to take a look at this: https://github.com/MisterJimson/flutter_keyboard_visibility/issues/50

**Comment by WXXXXH** [comment]
> Can you add more detail or a reproducible sample?
> 
> You may want to take a look at this: #50

thanks，solved the problem
