### ISSUE TITLE
Flutter 2.6 > FlutterKeyboardVisibilityPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by pantapita** [MisterJimson/flutter_keyboard_visibility#88]
flutter_keyboard_visibility-5.0.3/android/src/main/java/com/jrai/flutter_keyboard_visibility/FlutterKeyboardVisibilityPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by MisterJimson** [comment]
Yep! This is intended for folks who created their Android Flutter projects before v1.12. There is no issue with the warning, and it helps this package support more users.
