### ISSUE TITLE
Support having this plugin included in a Flutter Web app without breaking or throwing errors

### ISSUE THREAD

**Issue by nipunasudha** [MisterJimson/flutter_keyboard_visibility#9]
Could you please explain how would this plugin behave on Flutter web?

**Comment by MisterJimson** [comment]
This plugin current has no support for Flutter web and has not be tested with Flutter web.

**Comment by nipunasudha** [comment]
If possible, could you make sure the calls to this plugin are handled gracefully without errors on web platform? I think many people will be concerned about that as web is coming out of beta soon.

**Comment by MisterJimson** [comment]
That is a good idea. I've updated this issue to reflect.

**Comment by MisterJimson** [comment]
I was able to include this library in a Flutter web project without it introducing any issues. No errors. Going to close this issue. Feel free to open issues for specific bugs or feature requests related to web support.
