### ISSUE TITLE
Android V2 embedding

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [MisterJimson/flutter_keyboard_visibility#94]
Hi,

I get the following warning since I upgraded to Flutter 2.5.2. 

> The plugins `flutter_keyboard_visibility` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.

Is there any timeline on when this library will be upgraded to support this?

Thanks!

**Comment by MisterJimson** [comment]
5.1.0
